server:
  port: 8081
spring:
  application:
    name: MovieDb-Services-API-Gateway
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultzone: locahost:http/8761/Movie-Services-DiscoveryClient
zuul:
  routes:
    MovieDatabaseAppService:
      path: /Movie-Db-App/**
      service-id: Movie-Db-Service
      